docs: add faq docs on typescript
reactchartjs/react-chartjs-2 pull request #1042
Opened 2022-05-16 17:50 UTC by Arantiryo

2022-05-17 06:54 UTC, igorlukanin commented on website/docs/faq/docs.js
> +    title: 'How to use react-chartjs-2 with Typescript?',
```suggestion
    title: 'How to use react-chartjs-2 with TypeScript?',
```

2022-05-17 06:54 UTC, igorlukanin commented on website/docs/faq/typescript.md
> +# How to use react-chartjs-2 with Typescript?
```suggestion
# How to use react-chartjs-2 with TypeScript?
```

2022-05-17 06:55 UTC, igorlukanin commented on website/docs/faq/typescript.md
> +`Typescript` has extremely robust type inference capabilities and most of the time
```suggestion
TypeScript has extremely robust type inference capabilities and most of the time
```

2022-05-17 06:55 UTC, igorlukanin commented on website/docs/faq/typescript.md
> +and then used with `options` and `data` props.
```suggestion
...and then used with `options` and `data` props.
```

2022-05-17 06:56 UTC, igorlukanin commented on website/docs/faq/typescript.md
> +The generic being passed is a `ChartType` that can be one of the following values:
```suggestion
The generic ??? being passed is a `ChartType` that can be one of the following values:
```

I think a word is missing here. Generic type?

2022-05-17 15:40 UTC, dangreen requested changes

2022-05-17 15:40 UTC, dangreen commented on website/docs/faq/typescript.md
> +`TypeScript` has extremely robust type inference capabilities and most of the time
```suggestion
TypeScript has extremely robust type inference capabilities and most of the time
```

2022-05-17 15:40 UTC, dangreen commented on website/docs/faq/typescript.md
> +`bar`, `line`, `scatter`, `bubble`, `pie`, `doughnut`, `polarArea` or `radar`.
```suggestion
`'bar'`, `'line'`, `'scatter'`, `'bubble'`, `'pie'`, `'doughnut'`, `'polarArea'` or `'radar'`.
```

2022-05-19 10:03 UTC, dangreen approved these changes

2022-05-19 10:04 UTC, merged